### PR TITLE
Updated ReadMe to reflect changes to the decoder API

### PR DESCRIPTION
**Pull request by gerfen**
Updated the ReadMe to include the ```devEu``` parameter on the DecoderController route and updated the code samples to reflect the changes to the method signatures for decoder methods in LoraDecoders.

Note:  I was not able to change the image below to relfect the ```devEui`` URL parameter:
image

### CODE REVIEW

**Comment by TechPreacher** [comment]
Your change is spot on. Thank you for noticing and for your continued contributions!
I am happy to update the picture, if you give me permission to commit to your Pull Request branch by checking the "Allow edits from maintainers" checkbox on the Pull Request and letting me know. The feature is described here: https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork
Thanks!!!

**Comment by TechPreacher** [comment]
...or to make things easier for you, you could just copy the new image I created from:
https://1drv.ms/f/s!AhmOFqyXq7nBy91dOaU8_mlR-zRdRw
and add it to your existing PR...
Whichever way you prefer is fine with me!

**Comment by gerfen** [comment]
@TechPreacher Thanks to you and the rest of the team for all of your hard work on this project! I checked "Allow edits from maintainers" when I created the PR so I'm not sure why you are not able to edit?

image

If you are not able to edit I can try to add the image later today.

**Comment by gerfen** [comment]
@TechPreacher I figured out how to add the image to my PR.

**Comment by TechPreacher** [comment]
Perfect, thanks! Approving PR.

**Pull request merged**
