### PR TITLE
Fix MSB3030 error building device provisioning tool

### PR DESCRIPTION
**Pull request by atifaziz**
# PR for issue #1308

## What is being addressed

MSB3030 error building device provisioning tool due to missing when `appsettings.local.json` is missing locally.

## How is this addressed

Made the requirement of the file optional for building as it's also optional for configuration per line 33 of `ConfigurationHelper.cs`:

https://github.com/Azure/iotedge-lorawan-starterkit/blob/4490b3287bdc166a1d6b728d504abfb0b1377a6f/Tools/Cli-LoRa-Device-Provisioning/Helpers/ConfigurationHelper.cs#L30-L34

### CODE REVIEW

**Review by danigian — COMMENTED** [review]
As far as I understood, we were already including in the build something that might potentially include secrets from the Azure resources deployed.

What about just not including it?

**Comment by atifaziz** [comment]
> As far as I understood, we were already including in the build something that might potentially include secrets from the Azure resources deployed.
> 
> What about just not including it?

Local settings files are ignored by Git (so not included):

https://github.com/Azure/iotedge-lorawan-starterkit/blob/9a08055e1ae0450c6791984ad0aecac86e77d026/.gitignore#L295-L303

The project so far has assumed that the file is always there on disk, but that won't be the case for a fresh clone. The solutions in the repo should build for something that is a run-time requirement. In fact, I would argue that `appsettings.json` should be excluded at run-time and `appsettings.local.json` should be required! Right now, if someone modifies `appsettings.json` and puts credentials there (because `appsettings.local.json` is not technically needed) then they can get accidentally committed into Git. This fix is about getting the solution to build again. We should open another issue if we want to review how and where the CLI tool picks up the settings to lower the risk of accidents. What do you think?

**Comment by atifaziz** [comment]
BTW, just checked [our documentation](https://github.com/Azure/iotedge-lorawan-starterkit/blob/112d34826439841a204b8e6e09dc707cf070ba00/docs/tools/device-provisioning.md#setting-up) and it even recommends updating `appsettings.json`:

> [appsettings.json](https://github.com/Azure/iotedge-lorawan-starterkit/blob/dev/Tools/Cli-LoRa-Device-Provisioning/appsettings.json) needs to be in the same directory as the cli-lora-device-provisioning binary (verifyloradevice.dll or verifyloradevice.exe).
>
> [appsettings.json](https://github.com/Azure/iotedge-lorawan-starterkit/blob/dev/Tools/Cli-LoRa-Device-Provisioning/appsettings.json) needs to contain a connection string from the Azure IoT Hub you want to work with.

This is fine if someone didn't downloaded the sources, but I think there's a risk for accident if cloned.

**Comment by atifaziz** [comment]
@danigian I've logged #1335 to deal with the issue you've raised.

**Pull request merged**
