### PR TITLE
Support for Azure IoT Central 

### PR DESCRIPTION
**Pull request by kbeaugrand**
# PR for supporting Azure IoT Central for IoT device management

## What is being addressed

I don't know if this kind of feature was expected. But I was interressted to test this Starter Kit with IoT central for demonstration of the possibilities.

The objective was to adapt this project to enable the same deployment for Azure IoT Central for managing devices.

## How is this addressed

I created a dedicated interface for RegistryManger in the Facade with 2 implementations : 
- One for IoT Hub 
- One for IoT Central (based on REST APIs that are existing)

Since IoT Central leverage on IoT Hub and IoT DPS, The facade is able to registry dynamically the device during the LoRa Join step. But since the IoT Hub is assigned by the DPS, I had to provide as an outpout the IoT Hub Hostname that is assigned to the device (For IoT Hub implementation, I provided the IoT Hub that is used by the registry manager).

The network server catch the Assigned IoT Hub from the Join information to create the DeviceClient instance.

-> The API Version should be changed by doesn't create hard changes since this is only a new field taht is provided by the Facade.

## Unit Tests

I added some unit test to validate and verify the behavior of IoT Hub implementation and IoT Central's one.
I adpated existing UnitTests to fullfill the requirements.

**However I did not create or adapt any Integration Tests**

## What is missing

I sucessfully tested the device enrollement and device connectivity throught the Edge Gateway. 
However I was not able to set EnableGateway on the NetworkServer because of authenticating issues on the DeviceClient (I suspect to have a different IoT Hub for the Edge and the Leaf Device).

Please let me know If I can do more ?

### CODE REVIEW

**Comment by Mandur** [comment]
Hello @kbeaugrand, Thank you very much for this great contribution! 
We will start reviewing the PR, but due to its size, it might take some time.

**Comment by kbeaugrand** [comment]
Hi @Mandur, 

Thank you for your review !
Sorry for this PR's size however, since it requires many steps for me to handle this feature. 

But I know that's also might require some discussion internally because some of original features will not work with the IoT Central implementation for now... 

Please feel free to contact me if you want me to do some corrections...

**Comment by Mandur** [comment]
I will quickly need to close and open the pr to let it pass to our E2E environment, don't worry ;)

**Comment by kbeaugrand** [comment]
> I will quickly need to close and open the pr to let it pass to our E2E environment, don't worry ;)

Is there an issue with the CI ?

**Comment by Mandur** [comment]
I am sorry for the lack of updates; I was trying to have a better understanding of what was happening, but I was lacking an Arduino to test it (it just arrived today). 

Due to GitHub action limitation I had to fork your PR branch on the repo and run the end-to-end tests on it. The changes cause some issues (could not create IoT Hub device client with error: The connection string has an invalid value for property: HostName.), and I was going to investigate to give more details here. Here is [the run](https://github.com/Azure/iotedge-lorawan-starterkit/actions/runs/1265905437)

**Comment by kbeaugrand** [comment]
Hi @Mandur, 

I can see what is failing on the integration tests, however on my dev environment, I cannot launch these tests due to some configuration errors : 
```System.AggregateException : One or more errors occurred. (Failed to convert configuration value at 'testConfiguration:EnsureHasEventDelayBetweenReadsInSeconds' to type 'System.Int32'.) (The following constructor parameters did not have matching fixture data: IntegrationTestFixtureCi testFixture)
---- System.InvalidOperationException : Failed to convert configuration value at 'testConfiguration:EnsureHasEventDelayBetweenReadsInSeconds' to type 'System.Int32'.
-------- System.ArgumentException : #{INTEGRATIONTEST_EnsureHasEventDelayBetweenReadsInSeconds}# is not a valid value for Int32. (Parameter 'value')
------------ System.FormatException : Could not find any recognizable digits.
---- The following constructor parameters did not have matching fixture data: IntegrationTestFixtureCi testFixture
```

Do you have some documentation that I can follow to setup my environment as expected to run these integration tests ?

**Comment by Mandur** [comment]
Sure, you could follow guidance [here](https://github.com/Azure/<https://github.com/Azure/iotedge-lorawan-starterkit/tree/dev/LoRaEngine/test/LoRaWan.IntegrationTest>iotedge<https://github.com/Azure/iotedge-lorawan-starterkit/tree/dev/LoRaEngine/test/LoRaWan.IntegrationTest>-<https://github.com/Azure/iotedge-lorawan-starterkit/tree/dev/LoRaEngine/test/LoRaWan.IntegrationTest>lorawan<https://github.com/Azure/iotedge-lorawan-starterkit/tree/dev/LoRaEngine/test/LoRaWan.IntegrationTest>-<https://github.com/Azure/iotedge-lorawan-starterkit/tree/dev/LoRaEngine/test/LoRaWan.IntegrationTest>starterkit<https://github.com/Azure/iotedge-lorawan-starterkit/tree/dev/LoRaEngine/test/LoRaWan.IntegrationTest>/tree/dev/<https://github.com/Azure/iotedge-lorawan-starterkit/tree/dev/LoRaEngine/test/LoRaWan.IntegrationTest>LoRaEngine<https://github.com/Azure/iotedge-lorawan-starterkit/tree/dev/LoRaEngine/test/LoRaWan.IntegrationTest>/test/LoRaWan.IntegrationTest<https://github.com/Azure/iotedge-lorawan-starterkit/tree/dev/LoRaEngine/test/LoRaWan.IntegrationTest>). Do you have an Arduino seeeduino, our test harness are written for this device?
Otherwise I will do a local test run tomorrow on my setup I can let you know about the results

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kbeaugrand** [comment]
I have : 
Arduino Uno
Arduino nano
Esp 32 

But not seeduino ;(

**Comment by kbeaugrand** [comment]
Hi @Mandur, I fetched the upstream and try to add a fix that I found (unfortunatly without having tested it).

Could you re-launch your integration tests ?

**Comment by Mandur** [comment]
CI started on https://github.com/Azure/iotedge-lorawan-starterkit/actions/runs/1284013589
I am sorry I switched all my setup to the basic station. I am struggling to get the packet forwarder going, Looks like a firewall is intercepting the udp packets :/

**Comment by kbeaugrand** [comment]
Hi @Mandur,

I did a rebase from your dev branch to fix some merge conflicts. 

My seeduino has been shipped so I will be able to launch Integration test after I recieve it..

**Comment by kbeaugrand** [comment]
Thanks @Mandur, 
Glad to know you were able to restart your tests! ;)

It's interesting, sometimes the join seems to work, and in some cases not with this message: 

```
failed to get join devices from api. The connection string has an invalid value for property: HostName.
```

For my point of view it looks that for some reason the device getter is not returning the Assigned IoT Hub HostName as part of the DeviceId and Primary Key.

**Comment by Mandur** [comment]
@kbeaugrand We had a look with the team on the pr, and it looks quite good. Thank you very much! We will need to make some changes to make it compatible with ours plans. 
To be able to directly use our pipeline I added to the list of project's contributors (Welcome :P) so you could host your branch in the repo. I would suggest recreating the PR with an internal branch so our CI can run immediately.
In the next day, we will have a deeper look at the code to really own and understand the architectural decision.
@atifaziz @spygi

**Comment by kbeaugrand** [comment]
Hi @Mandur, 

Many thanks for being part of this project (at least for this Pull Request) !

As we discussed, this PR is now closed.
 
I Successfully pushed a branch to your repository ``feature/iot-central`` an making a new PR from this one : [https://github.com/Azure/iotedge-lorawan-starterkit/pull/731](https://github.com/Azure/iotedge-lorawan-starterkit/pull/731).

**Pull request closed without merging**
