### PR TITLE
Added StationEui to LoRaDeviceTelemetry (#1357)

### PR DESCRIPTION
**Pull request by gerfen**
# PR for issue #1357

## What is being addressed
Adding StationEui to messages sent to Azure IoT Hub.

The StationEui is currently not sent to Azure IoT Hub.  This PR adds that property to the LoRaDeviceTelemetry class.
## How is this addressed
Added StationEui property which is set from the StationEui property of LoRaRequestpassed to the LoRaDeviceTelemetry constructor.

### CODE REVIEW

**Review by danigian — CHANGES_REQUESTED** [review]
Hi @gerfen and thanks for your contribution, it is really appreciated!

Unfortunately, this PR would need some more work to fix some failing tests (LoRaWan.Tests.Integration.DecoderTests)

Is it something you could work on?

**Comment by gerfen** [comment]
@danigan I will take a look at the tests.  It doesn't look too difficult to fix them.

**Comment by gerfen** [comment]
@danigian The tests are fixed.  Please let me know if there is anything else I can do.

**Review by danigian — APPROVED** [review]

**Comment by danigian** [comment]
Thanks for your contribution @gerfen
I have merged the PR right now

**Pull request merged**
